### ISSUE TITLE
How to unhide entity

### ISSUE THREAD

**Issue by clinta** [MarkGodwin/hacs_gamma_light#1]
As noted in the bottom of the readme, you can end up with a problematically hidden entity that can't be easily unhidden. What is the not easy way to unhide it?

I got in this situation cause I wanted to rename the underlying entity ID, so that the adjusted entity could take over and I wouldn't have to adjust my groups or automations. But when I renamed the underlying entity ID, I broke the adjusted entity, then I deleted the adjusted entity and now my light is stuck hidden.

**Comment by clinta** [comment]
Solved myself. Edit `config/core.entity_registry` and change `hidden-by` from `"integration"` to `null`. Then restart homeassistant.

**Comment by MarkGodwin** [comment]
Thanks for the feedback. I’m not sure there’s much I can do to keep the entity ID of the underlying entity.
Well done for figuring out the fix, and thanks for sharing.
Out of interest, did the HACS repo work for you, or did you install the component manually?

**Comment by clinta** [comment]
I installed via HACS. It's working great. The gamma adjust is very helpful for some of my shelly dimmers attached to cheap LEDs that seem to only have any dynamic range between 0 and 20 %.
