### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mikulik86** [MarkGodwin/hacs_gamma_light#2]
When I try to create the Helper, HA gives me an Error: 
"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by MarkGodwin** [comment]
Yeah, I see the same thing in the latest version of HA. I'll look into it.

**Comment by MarkGodwin** [comment]
I've updated the code to support the HA 2022.12 release.

**Comment by mikulik86** [comment]
Thank you. Works great!
