### ISSUE TITLE
Would it be possible to add percentage limits?

### ISSUE THREAD

**Issue by robsonfelix** [MarkGodwin/hacs_gamma_light#5]
I am using a Sonoff D1 dimmer and in some occasions it turns the light off if set the brightness above a given limit, or it will not light up given a minimum brightness. Instead of hard-coding it into the device itself I would rather have this in an integration like yours.

Is this possible?

Cheers!

**Comment by MarkGodwin** [comment]
Yeah, it should be pretty easy to add a maximum as well as a minimum. If I have time this weekend I will have a look at doing it.

**Comment by MarkGodwin** [comment]
I've added the feature. Let me know how it goes.

**Comment by bazb** [comment]
The max works great. Thanks. This addon exactly fits my needs.

**Comment by MarkGodwin** [comment]
Glad to hear it :)

**Comment by arquloco** [comment]
Hey MarkGodwin, i cant open a new issue, so i had to make do here. 
This helper seems to be exactly what i need, but i cant find it in HACS, have you stopped supporting it?
